### ISSUE TITLE
Improve performance / speed

### ISSUE THREAD

**Issue by antoniocgodoi** [venturi123/DRLinFluids#21]
Hi,

Thank you very much for your excellent work!
I'm simulating the square VIV multiprocessing example to understand and eventualy modify it.
We are running the training on a fast computer, 32-core Intel i9 14900K, but it takes days to process.
How could we set the parameters to improve speed?
Can we just multiply the env* folders (by using cp env01 envXX) and running python launch_multiprocessing_traning_square2D_VIV.py --training-num XX.

**Comment by venturi123** [comment]
Hey @antoniocgodoi ,

To speed up the training, the first approach is to improve computational efficiency by using CFD parallel computing to leverage multi-core performance fully. However, due to I/O limitations, more parallel processes don’t always guarantee faster performance, especially for simpler cases. The second approach is to enhance DRL training efficiency. As you mentioned, copying the `env*` folders, numbering them sequentially, and using the `--training-num` flag is feasible. Additionally, optimizing neural network parameters also helps accelerate convergence.

**Comment by antoniocgodoi** [comment]
Thank you very much for your prompt answer!
