### ISSUE TITLE
pass tests

### ISSUE THREAD

**Issue by jerabaul29** [venturi123/DRLinFluids#5]

**Comment by jwcy0529** [comment]
Hello. Your job is of great help to my research. Thank you for opening up such a good job. I encountered a small problem when using docker to reproduce your work. Can you help me solve it ? When the terminal runs the launch_multiprocessing_traning_square.py file, the error is reported as follows :

$ vi launch_multiprocessing_traning_square.py
$ cd ..
$ python DRLinFluids_square/launch_multiprocessing_traning_square.py
/Drlinfluids/Square2D_Multiprocessing
['env01', 'env02', 'env03', 'env04', 'env05', 'env06']
/bin/bash: decomposePar: command not found
Traceback (most recent call last):
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 369, in <module>
    test_sac_with_il()
  File "DRLinFluids_square/launch_multiprocessing_traning_square.py", line 160, in test_sac_with_il
    env = envobject_square.FlowAroundSquare2D(
  File "/DRLinfluids/square2D_multiprocessing/DRLinFluids_square/DRLinFluids/environments_tianshou.py", line 112, in __init__
    cfd.run_init(foam_root_path, foam_params)
  File "/DRLinfluids/square2D_multiprocessing/DRLinFluids_square/DRLinFluids/utils.py", line 414, in wrapper
    func(*args, **kwargs)
  File "/DRLinfluids/square2D_multiprocessing/DRLinFluids_square/DRLinFluids/cfd.py", line 134, in run_init
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /DRLinfluids/square2D_multiprocessing/env01 && decomposePar -force > /dev/null' returned non-zero exit status 127.

In order to find the problem, I added print print(root_path.title())，print(env_name_list). Printed the correct results. At the same time according to the code: cd /DRLinfluids/square2D_multiprocessing/env01 && decomposePar -force, should be forced to decomposePar. I don 't know why will report error. What puzzles me is that I downloaded the complete DRLinfluids folder from the doker's File, and ran it with VS under WSL but was able to run normally. I repeatedly checked the running start folder, did not find the problem. Could you please look at this problem for me? Thank you for your time and look forward to your reply.

**Comment by venturi123** [comment]
Hi @jwcy0529 ,

This error may be due to an incorrect configuration of the OpenFOAM environment in your code. If you are not using the Docker/Singularity environment we provided, please check if [this line](https://github.com/venturi123/DRLinFluids-examples/blob/bd9908779ebb5757ccb8366864c70ce5747a0e35/examples/square2D_multiprocessing/DRLinFluids_square/launch_multiprocessing_traning_square.py#L95) of code is appropriately configured. In addition, we highly recommend using the Docker/Singularity environment for training. You can modify and test based on the two cases we provided, which can avoid various errors caused by configuring the environment. 

P.S. In my personal experience, WSL is not a good development environment for using DRLinFLuids and may cause some strange errors. If you must set up a simulation environment on your own, I recommend using a real physical machine or a virtual machine similar to VirtualBox.

Best,
Qiulei

**Comment by venturi123** [comment]
Hi @jiangzhangze ,

It seems that you are using your local conda environment, not the built-in one. Could you please show me the command for launching the script?

Besides, are you running on an HPC Cluster?

**Comment by jiangzhangze** [comment]
I run it on my local machine.
Here are the full command:
```
singularity shell DRLinfluids.sif
drl
cd DRLinfluids/examples/cylinder2D_mulyiprocessing

python DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py
```

> Hi @jiangzhangze ,
> 
> It seems that you are using your local conda environment, not the built-in one. Could you please show me the command for launching the script?
> 
> Besides, are you running on an HPC Cluster?

**Comment by jerabaul29** [comment]
@jiangzhangze  can you try to follow exactly the instructions from the comment:

https://github.com/venturi123/DRLinFluids/issues/10#issuecomment-1632940312

?

**Comment by jiangzhangze** [comment]
Hi @jerabaul29 I can train it follow this comment.Do I need to follow this comment every time I enter the image?

**Comment by jiangzhangze** [comment]
What should I do if I want to start a experiment without network such as HPC clutser

**Comment by jiangzhangze** [comment]
Hi @venturi123 and @jerabaul29 .I mean that how to skip the `git clone https://github.com/venturi123/DRLinFluids.git` .I have tried to bind `DRLinFluids` directory when shell the sif， but it seems doesn't work.

**Comment by venturi123** [comment]
I may not understand what happened. But I think you can download the DRLinFluids container and the whole repository first. Then upload both of them to the cluster.

PS. The `bind` flag aims to bind your external storage device only, please check the [note](https://github.com/venturi123/DRLinFluids#examples) section.
